#!/usr/bin/env python3
"""Backfill the air_quality table from an AirGradient CSV export.

The export reaches further back than the bridge has been running, so this is
how history predating the first poll gets in. Rows are keyed on the UTC
timestamp snapped to a 5-minute bucket, matching how readings are stored, and
written with INSERT OR REPLACE so re-running is safe.

Prefers AirGradient's *corrected* columns, matching what the live API client
does, so backfilled and polled rows are the same measurement.

Usage:
    python scripts/backfill_air_csv.py "air-gradient-export/export (1).csv" > backfill.sql
    turso db shell daikin < backfill.sql
"""
import csv
import datetime
import io
import sys

BUCKET_SEC = 300
CHUNK = 200  # rows per INSERT statement


def parse_utc(s):
    """The export writes UTC as ISO 8601 with a Z suffix."""
    s = s.strip().replace("Z", "+00:00")
    return datetime.datetime.fromisoformat(s)


def num(row, *names):
    """First present, non-empty, numeric value among the candidate columns."""
    for n in names:
        v = (row.get(n) or "").strip()
        if v == "":
            continue
        try:
            return float(v)
        except ValueError:
            continue
    return None


def sql_val(v):
    return "NULL" if v is None else repr(round(v, 3))


def main(path):
    rows = {}
    for r in csv.DictReader(io.open(path, encoding="utf-8-sig")):
        utc = (r.get("UTC Date/Time") or "").strip()
        if not utc:
            continue
        ts = int(parse_utc(utc).timestamp())
        ts = (ts // BUCKET_SEC) * BUCKET_SEC
        rows[ts] = (
            num(r, "Temperature (°C) corrected", "Temperature (°C) raw"),
            num(r, "Humidity (%) corrected", "Humidity (%) raw"),
            num(r, "CO2 (ppm) corrected", "CO2 (ppm) raw"),
            num(r, "PM2.5 (μg/m³) corrected", "PM2.5 (μg/m³) raw"),
            num(r, "PM1 (μg/m³)"),
            num(r, "PM10 (μg/m³)"),
            num(r, "0.3μm particle count"),
            num(r, "TVOC index"),
            num(r, "NOX index"),
        )

    ordered = sorted(rows.items())
    print("-- Generated by scripts/backfill_air_csv.py. Safe to re-run.")
    print(f"-- {len(ordered)} rows from {path}")
    if ordered:
        lo = datetime.datetime.fromtimestamp(ordered[0][0], datetime.timezone.utc)
        hi = datetime.datetime.fromtimestamp(ordered[-1][0], datetime.timezone.utc)
        print(f"-- span {lo} .. {hi} UTC\n")

    cols = ("ts, temp_c, rh, co2, pm02, pm01, pm10, pm003_count, "
            "tvoc_index, nox_index, source")
    for i in range(0, len(ordered), CHUNK):
        chunk = ordered[i:i + CHUNK]
        values = ",\n  ".join(
            "(" + str(ts) + "," + ",".join(sql_val(v) for v in vals) + ",'csv')"
            for ts, vals in chunk
        )
        print(f"INSERT OR REPLACE INTO air_quality ({cols}) VALUES\n  {values};")

    print(f"\n-- {len(ordered)} rows emitted", file=sys.stderr)


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "air-gradient-export/export.csv")
